const Cards = [
  {
    BinNumber: "Bin Number",
    Issuing_Bank: "Issuing Bank",
    CardScheme: "Card Scheme",
    CardType: "Card Type",
  },
  {
    BinNumber: 438628,
    Issuing_Bank: "CITI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 472642,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 517252,
    Issuing_Bank: "SBI",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 533467,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 536907,
    Issuing_Bank: "RBL",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 437551,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 489377,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 545964,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 416021,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 402985,
    Issuing_Bank: "BOB",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 525611,
    Issuing_Bank: "RBL",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 451457,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 524373,
    Issuing_Bank: "RBL",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 549777,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 485498,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 461119,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 420739,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 530562,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 428090,
    Issuing_Bank: "KOTAK",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 431581,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 437748,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 552260,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 518159,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 541919,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 404745,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 517725,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 463917,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 459453,
    Issuing_Bank: "KOTAK",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 552137,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 469198,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 554637,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 552365,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 428094,
    Issuing_Bank: "KOTAK",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 524181,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 512967,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 433587,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 524182,
    Issuing_Bank: "SBI",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 516640,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 528677,
    Issuing_Bank: "CANARA",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 559342,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 434155,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 415575,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 405988,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 523950,
    Issuing_Bank: "RBL",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 438976,
    Issuing_Bank: "PAYTM",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 417349,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 472254,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 457262,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 468779,
    Issuing_Bank: "CANARA",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 534680,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 474846,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 438106,
    Issuing_Bank: "CITI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 408849,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 433588,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 469197,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 538103,
    Issuing_Bank: "YES",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 479932,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 463237,
    Issuing_Bank: "DBS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 464118,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 438624,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 461680,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 434168,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 460133,
    Issuing_Bank: "CANARA",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 457704,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 553583,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 483834,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 558983,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 401704,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 536610,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 470011,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 431393,
    Issuing_Bank: "BOB",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 401806,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 524247,
    Issuing_Bank: "SBI",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 421328,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 411146,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 510223,
    Issuing_Bank: "SBI",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 435376,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 435616,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 450503,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 451456,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 523650,
    Issuing_Bank: "RBL",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 522346,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 400667,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 403562,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 552385,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 533112,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 361135,
    Issuing_Bank: "HDFC",
    CardScheme: "Diners",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 430463,
    Issuing_Bank: "CITI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 533114,
    Issuing_Bank: "YES",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 549852,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 514834,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 522358,
    Issuing_Bank: "YES",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 541608,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 414367,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 528734,
    Issuing_Bank: "SBI",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 522012,
    Issuing_Bank: "RBL",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 529117,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 403009,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 437546,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 532662,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 539149,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 544365,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 534424,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 526702,
    Issuing_Bank: "YES",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 524133,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 414366,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 468957,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 368357,
    Issuing_Bank: "HDFC",
    CardScheme: "Diners",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 559405,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 360886,
    Issuing_Bank: "HDFC",
    CardScheme: "Diners",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 498792,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 435502,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 468743,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 428099,
    Issuing_Bank: "KOTAK",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 524178,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 436303,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 430832,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 435584,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 536621,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 547359,
    Issuing_Bank: "SBI",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 522852,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 486461,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 512932,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 461116,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 529375,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 524317,
    Issuing_Bank: "SBI",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 438587,
    Issuing_Bank: "CITI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 361011,
    Issuing_Bank: "HDFC",
    CardScheme: "Diners",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 461795,
    Issuing_Bank: "CITI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 410202,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 535985,
    Issuing_Bank: "YES",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 485446,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 403250,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 559404,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 418210,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 555378,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 415382,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 536298,
    Issuing_Bank: "SBI",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 461118,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 428091,
    Issuing_Bank: "KOTAK",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 471860,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 450504,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 428096,
    Issuing_Bank: "KOTAK",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 520386,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 532676,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 559725,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 430570,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 401403,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 409638,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 434158,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 407352,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 536016,
    Issuing_Bank: "YES",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 529616,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 419188,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 529252,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 518145,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 524877,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 468742,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 490015,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 431757,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 536132,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 361010,
    Issuing_Bank: "HDFC",
    CardScheme: "Diners",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 529617,
    Issuing_Bank: "YES",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 438114,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 526468,
    Issuing_Bank: "SBI",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 524254,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 517550,
    Issuing_Bank: "YES",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 430833,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 529372,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 528678,
    Issuing_Bank: "CANARA",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 460214,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 455038,
    Issuing_Bank: "CITI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 539192,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 456407,
    Issuing_Bank: "CITI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 522306,
    Issuing_Bank: "YES",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 452572,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 549778,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 420580,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 526419,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 461797,
    Issuing_Bank: "CITI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 512622,
    Issuing_Bank: "SBI",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 430834,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 465514,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 531858,
    Issuing_Bank: "SBI",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 468799,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 450172,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 222855,
    Issuing_Bank: "YES",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 510128,
    Issuing_Bank: "SBI",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 524482,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 529618,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 431459,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 463918,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 434301,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 431731,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 510135,
    Issuing_Bank: "SBI",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 542505,
    Issuing_Bank: "RBL",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 428098,
    Issuing_Bank: "KOTAK",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 559341,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 469191,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 477037,
    Issuing_Bank: "CANARA",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 523996,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 417380,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 405533,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 421006,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 450506,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 431418,
    Issuing_Bank: "KOTAK",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 532663,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 537687,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 526106,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 532973,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 361153,
    Issuing_Bank: "HDFC",
    CardScheme: "Diners",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 490906,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 468949,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 553683,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 555153,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 486410,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 485455,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 527536,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 461786,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 406597,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 222940,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 524240,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 549533,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 222849,
    Issuing_Bank: "YES",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 432198,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 541497,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 434302,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 455390,
    Issuing_Bank: "CITI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 533136,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 529629,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 542541,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 400782,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 469190,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 488994,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 529495,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 490247,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 401767,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 559340,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 420416,
    Issuing_Bank: "BOB",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 531662,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 450170,
    Issuing_Bank: "DBS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 432727,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 409642,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 512525,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 542705,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 448197,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 471865,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 490246,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 222709,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 553682,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 405995,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 457392,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 512968,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 416317,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 524451,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 428306,
    Issuing_Bank: "KOTAK",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 529819,
    Issuing_Bank: "CANARA",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 517848,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 532961,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 433662,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 459247,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 478748,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 415623,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 431754,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 537654,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 413531,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 406894,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 420132,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 519522,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 409542,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 428097,
    Issuing_Bank: "KOTAK",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 425880,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 549779,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 436543,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 450502,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 451104,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 222857,
    Issuing_Bank: "YES",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 524508,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 527625,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 436371,
    Issuing_Bank: "DBS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 420084,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 559145,
    Issuing_Bank: "YES",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 463919,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 526905,
    Issuing_Bank: "CANARA",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 490289,
    Issuing_Bank: "DBS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 401920,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 542572,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 527114,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 549177,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 529374,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 532127,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 470939,
    Issuing_Bank: "CANARA",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 445084,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 476658,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 479966,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 428093,
    Issuing_Bank: "KOTAK",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 544170,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 367123,
    Issuing_Bank: "HDFC",
    CardScheme: "Diners",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 522318,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 559469,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 401798,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 523429,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 451460,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 428095,
    Issuing_Bank: "KOTAK",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 436560,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 222848,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 474865,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 485905,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 361152,
    Issuing_Bank: "HDFC",
    CardScheme: "Diners",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 559939,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 404276,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 440006,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 519860,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 415641,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 552274,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 542464,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 436391,
    Issuing_Bank: "DBS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 529185,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 483851,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 527274,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 524931,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 413289,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 436534,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 419952,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 524512,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 515566,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 531831,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 222708,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 401772,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 401784,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 407984,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 452574,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 222853,
    Issuing_Bank: "YES",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 222856,
    Issuing_Bank: "YES",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 418212,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 436152,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 535960,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 539189,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 401780,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 465573,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 532731,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 421137,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 445068,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 436369,
    Issuing_Bank: "DBS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 545226,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 553162,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 421424,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 511382,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 532666,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 524368,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 402853,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 400843,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 534460,
    Issuing_Bank: "RBL",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 549751,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 476643,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 415053,
    Issuing_Bank: "CANARA",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 465511,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 428348,
    Issuing_Bank: "KOTAK",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 517215,
    Issuing_Bank: "RBL",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 524458,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 527479,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 532734,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 406228,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 461796,
    Issuing_Bank: "CITI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 410852,
    Issuing_Bank: "DBS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 512963,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 517435,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 406583,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 415625,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 405393,
    Issuing_Bank: "KOTAK",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 537905,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 555219,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 420125,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 420134,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 435736,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 478286,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 423364,
    Issuing_Bank: "BOB",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 450171,
    Issuing_Bank: "DBS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 526268,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 436306,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 467742,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 470496,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 472643,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 476641,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 534044,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 439359,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 469645,
    Issuing_Bank: "KOTAK",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 400666,
    Issuing_Bank: "SBI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 537903,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 555381,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 511870,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 511872,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 514833,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 522352,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 526701,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 533102,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 539158,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 559493,
    Issuing_Bank: "AXIS",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 405997,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 421539,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 445069,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 470328,
    Issuing_Bank: "AXIS",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 467029,
    Issuing_Bank: "BOB",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 526421,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 540175,
    Issuing_Bank: "CITI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 559300,
    Issuing_Bank: "HDFC",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 461787,
    Issuing_Bank: "HDFC",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 511414,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 511416,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 516107,
    Issuing_Bank: "ICICI",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 447758,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 486536,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 409513,
    Issuing_Bank: "ICICI",
    CardScheme: "VISA",
    CardType: "DEBIT CARD",
  },
  {
    BinNumber: 549489,
    Issuing_Bank: "RBL",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 554703,
    Issuing_Bank: "RBL",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 555331,
    Issuing_Bank: "RBL",
    CardScheme: "MasterCard",
    CardType: "CREDIT CARD",
  },
  {
    BinNumber: 530557,
    Issuing_Bank: "YES",
    CardScheme: "MasterCard",
    CardType: "DEBIT CARD",
  },
];
module.exports = Cards;
